# Generated by Django 4.1.7 on 2023-03-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modani_app', '0003_product_quantity_sale_like_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale',
            new_name='percent',
        ),
    ]
