# Generated by Django 4.1.7 on 2023-03-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modani_app', '0005_rename_name_sub_category_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_dimensions',
            field=models.TextField(max_length=500),
        ),
    ]
